# Dynamic configuration
http:
  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # Redirect with domain replacement
    main-redirect:
      redirectRegex:
        regex: "^https://your.domain/(.*)"
        replacement: "https://www.your.domain/${1}"
    
    # Redirect blog with domain replacement
    blog-redirect:
      redirectRegex:
        regex: "^https://your.domain/(.*)"
        replacement: "https://www.your.domain/${1}"

    user-auth:
      basicAuth:
        users:
          - "user:password"

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12